//eventos de scroll

// En JavaScript para navegadores, el objeto window es el corazón de todo. Representa la ventana del navegador que contiene el DOM y actúa como el objeto global.Si declaras una variable global o una función (usando var), automáticamente se convierte en una propiedad de window.¿Qué funciones cumple window?Se puede dividir su utilidad en tres pilares principales:1. El Objeto GlobalEn el entorno del navegador, window es el contenedor de nivel superior. Todo lo que JavaScript "conoce" por defecto vive aquí:Variables globales: Si escribes var saludo = "Hola", puedes acceder a él como window.saludo.Funciones integradas: Métodos como alert(), setTimeout() o fetch() son en realidad window.alert(), window.setTimeout(), etc.2. Control del Navegador (BOM)El BOM (Browser Object Model) permite a JavaScript interactuar con el navegador fuera de la página web. A través de window puedes acceder a:window.location: Para ver o cambiar la URL actual.window.history: Para navegar atrás o adelante en el historial.window.localStorage: Para guardar datos de forma persistente en el navegador.window.innerWidth / innerHeight: Para conocer el tamaño de la ventana.3. Acceso al DOMAunque solemos usar simplemente document, este es en realidad una propiedad de la ventana: window.document. Es el punto de entrada para manipular el HTML.Un detalle importante: window vs globalThisHistóricamente, cada entorno de JavaScript tenía un nombre distinto para el objeto global:En el navegador: window.En Node.js: global.En Web Workers: self.Para evitar confusiones, hoy en día existe globalThis, que es una forma estándar de referirse al objeto global sin importar dónde se esté ejecutando el código. En el navegador, globalThis === window es true.Diferencias clave entre window y documentEs común confundirlos al principio, pero tienen roles muy distintos:CaracterísticawindowdocumentRepresentaLa ventana completa del navegador.La página HTML cargada.JerarquíaEs el padre de document.Es hijo de window.Ejemplo de usoCerrar la ventana o detectar el scroll.Cambiar un texto o un color de fondo.

//si queremos escuchar por el scroll de la pagina utilizamos la ventana global window
window.addEventListener("scroll",()=>{
    console.log("scrolling...")
    const scrollPixeles=window.scrollY//asi capturo los pixeles a los que se le estan haciendo scroll
    console.log(scrollPixeles)
})

